name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
        - '**'
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Test - Ubuntu, Python 3.12
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Ensure 'test-plots' directory exists
      run: mkdir -p ~/.chia/test-plots

    - name: Cache 'test-plots' directory
      uses: actions/cache@v4
      with:
        path: ~/.chia/test-plots
        key: test-plots
        restore-keys: test-plots

    - name: Setup python3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12' 
        cache: 'pip'

    - name: Install other required libraries
      run: python3 -m pip install -r requirements.txt && python3 -m pip install -r requirements-testing.txt

    - name: Test code with pytest
      run: pytest tests/ -s -v --durations 0 -W ignore::DeprecationWarning
